### ISSUE TITLE
Properties with boolean type are been removed from result

### ISSUE THREAD

**Issue by karlaugust1** [marquesVF/objectypes#347]
I have stored in a database an object which has the attribute `foo` (type boolean) as `true`. After the object been found in the dababase, I use `buildObject` function to adapt the object from database to the class from my domain. With a few tests in my API, I've noticed that when the attribute `foo` is `false`, the attribute does not map in the final result. For example:
```typescript
class MyObject {
@Property()
name: string
@Property({ nullable: true, defaultValue: false })
foo: boolean
}

const test = {
name: 'my-test',
foo: false
}

buildObject(MyObject, test)

// The result is: { name: 'my-test' }
```

**To Reproduce**

1. Create an object with some attribute with the type `boolean` and add the decorator @Property
2. Set the value of the property as false
3. Use buildObject from lib to convert to the object

**Expected behavior**
The value of any boolean property to be mapped to the final object

**Screenshots**
![image](https://github.com/marquesVF/objectypes/assets/32959933/e045d64d-373a-4dcc-a2c4-ffd8fe2f3dcd)
![image](https://github.com/marquesVF/objectypes/assets/32959933/970f8ecc-8341-4907-b2b6-a759456b0eac)

- OS: Windows 11 Home
- Version: 22H2
- Node: v18.18.0
- Typescript: 4.4.4
- ts-node: 8.6.2

**Comment by marquesVF** [comment]
Hi, @karlaugust1.

Thanks for the excellent issue description.

I fixed the issue [here](https://github.com/marquesVF/objectypes/pull/348) and published a new version on npm.

Please update to version 1.3.1.
